server:
  port: 8080

spring:
  application:
    name: spring-boot-ollama-chatbot
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

# Ollama Configuration
ollama:
  base-url: http://localhost:11434
  model: tinyllama

# Logging Configuration
logging:
  level:
    com.example.chatbot: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
